#!/bin/bash

## 
## PRE-CHECK
## 

[[ `VBoxManage -version | grep 'command not found'` ]] && echo "Could not find VirtualBox. Please install before proceeding." && exit 1
[[ `vagrant version | grep 'command not found'` ]] && echo "Could not find Vagrant. Please install before proceeding." && exit 1


## 
## VARIABLES
## 

self=$0
command=$1
args=$2
rundir=`pwd`
STRUCTOR_HOME=${STRUCTOR_HOME:-"/Users/$USER/workspace/structor"}
STRUCTOR_CONFIG="${STRUCTOR_HOME}/.config"
ls -l $STRUCTOR_CONFIG
source "${STRUCTOR_CONFIG}" 2>/dev/null
STRUCTOR_PROFILE=${STRUCTOR_PROFILE:-"4node-nonsecure"}
STRUCTOR_PROFILE_DIR=${STRUCTOR_PROFILE_DIR:-"${STRUCTOR_HOME}/profiles/labs"}

##
## FUNCTIONS
##

function PrintHelp {
  echo "Usage:"
  echo -e "$self \tstart <name>\t- Start the virtual cluster for lab <name>"
  echo -e "\t\tdns\t\t- Add hosts in current profile to /etc/hosts"
  echo -e "\t\tdestroy\t\t- Destroy the active cluster"
  echo -e "\t\tstatus [<host>]\t- List all hosts, or show status of specified host"
  echo -e "\t\tssh <host>\t- ssh to the specified host"
  echo -e "\t\thelp\t\t- Print this help message"
  exit 0
}

function StartProfile {
  [ ! $args ] && echo "No profile specified, exiting" && exit 1
  SetProfile $args
  Deploy
}

function SetProfile {
  [ ! $args ] && echo "No profile specified, exiting" && exit 1

  profile_home="${STRUCTOR_PROFILE_DIR}/${args}"
  profile_error=0

  # Verify profile contains required files
  [ ! -d "${profile_home}" ] && echo "Profile directory ${profile_home} does not exist" && (( profile_error++ ))
  [ ! -f "${profile_home}/structor.json" ] && echo "Profile missing structor.json" && (( profile_error++ ))
  [ ! -f "${profile_home}/blueprint.json" ] && echo "Profile missing blueprint.json" && (( profile_error++ ))
  [ ! -f "${profile_home}/hostgroups.json" ] && echo "Profile missing hostgroups.json" && (( profile_error++ ))
  [ ! -f "${profile_home}/hdp.repo" ] && echo "Profile missing hdp.repo" && (( profile_error++ ))
  [ ! -f "${profile_home}/ambari.repo" ] && echo "Profile missing ambari.repo" && (( profile_error++ ))
  [ $profile_error -gt 0 ] && echo "Error setting new profile, exiting." && ListActiveProfile && exit 1

  # Set new active profile
  export STRUCTOR_PROFILE=$args

  # Copy files into place
  rm -f ${STRUCTOR_HOME}/current.profile # && echo "Removed old structor/current.profile"
  ln -s ${profile_home}/structor.json ${STRUCTOR_HOME}/current.profile # && echo "Set structor/current.profile -> ${STRUCTOR_PROFILE}/structor.json"
  cp -a ${profile_home}/hdp.repo ${STRUCTOR_HOME}/files/repos/hdp.repo # && echo "Set structor hdp.repo"
  cp -a ${profile_home}/ambari.repo ${STRUCTOR_HOME}/files/repos/ambari.repo # && echo "Set structor ambari.repo"

  # Update .config file
  conf_file=${STRUCTOR_CONFIG}
  if [ -f "${conf_file}" ]; then
    if [ `grep 'STRUCTOR_PROFILE' $conf_file | wc -l` -gt 0 ]; then
      text_replace="s/STRUCTOR_PROFILE=.*/STRUCTOR_PROFILE=${STRUCTOR_PROFILE}/g"
      sed -e "${text_replace}" -i .bak "${conf_file}"
    else
      echo "STRUCTOR_PROFILE=${STRUCTOR_PROFILE}" >> ${conf_file}
    fi
  fi

  # SetProfile complete
  ListActiveProfile
  echo "Update /etc/hosts by executing: $self dns"

}

function ListActiveProfile {
  echo ''
  echo "Active profile: ${STRUCTOR_PROFILE}"
  echo ''
}

function ListProfiles {
  echo 'Available profiles:'
  ls -1 ${STRUCTOR_PROFILE_DIR}
  ListActiveProfile
}

function UpdateDns {
  uhpath="${STRUCTOR_PROFILE_DIR}/${STRUCTOR_PROFILE}/update-hosts.sh"
  [ ! -e "${uhpath}" ] && echo "Profile missing update-hosts.sh, make edits manually" && exit 1
  [ ! -x "${uhpath}" ] && echo "Profile unable to execute update-hosts.sh, make edits manually" && exit 1
  $uhpath
}

function Deploy {
  cd ${STRUCTOR_HOME}
  vagrant up --provider virtualbox
  cd $rundir

  # Apply Blueprint - TODO: make non-fqdn specific
  #ApplyBlueprint mgmt.support.local

}

function Status {
  args=$1
  echo ${STRUCTOR_HOME}
  cd ${STRUCTOR_HOME}
  vagrant status $args
  cd "$rundir"
}

function Halt {
  cd "${STRUCTOR_HOME}"
  vagrant status | grep virtualbox | grep running | awk '{print $1}' | xargs vagrant halt
  cd "$rundir"
}

function Suspend {
  cd "${STRUCTOR_HOME}"
  vagrant status | grep virtualbox | grep running | awk '{print $1}' | xargs vagrant suspend
  cd "$rundir"
}

function Resume {
  cd "${STRUCTOR_HOME}"
  vagrant status | grep virtualbox | grep saved | awk '{print $1}'| xargs vagrant resume
  vagrant status | grep virtualbox | grep running | awk '{print $1}'| xargs vagrant reload
  cd "$rundir"
}

function Destroy {
  read -r -p "CLUSTER WILL BE DESTROYED!  Type 'yes' to proceed, anything else to cancel: " input
  [ $input != "yes" ] && echo "Exiting." && exit 0
  
  cd "${STRUCTOR_HOME}"
  vagrant status | grep virtualbox | awk '{print $1}' | xargs vagrant destroy -f
  cd "$rundir"
}

function SSH {
  echo ''
  echo ''
  echo 'To become root in the VM: sudo su -'
  echo ''
  echo ''
  cd ${STRUCTOR_HOME}
  vagrant ssh $args
  cd "$rundir"
}

# TODO: make blueprint name pluggable
function ApplyBlueprint {
  AmbariHost=$1
  profile_home="${STRUCTOR_PROFILE_DIR}/${STRUCTOR_PROFILE}"
  BlueprintFile=${profile_home}/blueprint.json
  HostgroupsFile=${profile_home}/hostgroups.json
  ls -l $profile_home
  [ ! "${AmbariHost}" ] && echo "No Ambari host supplied, exiting" && exit 1
  [ ! -e "${BlueprintFile}" ] && echo "Blueprint file not found, exiting" && exit 1
  [ ! -e "${HostgroupsFile}" ] && echo "Hostgroups file not found, exiting" && exit 1
  echo "Applying blueprint..."
  curl --user admin:admin -H 'X-Requested-By:mycompany' -X POST http://${AmbariHost}:8080/api/v1/blueprints/hdpcluster -d @${BlueprintFile}
  curl --user admin:admin -H 'X-Requested-By:mycompany' -X POST http://${AmbariHost}:8080/api/v1/clusters/hdpcluster -d @${HostgroupsFile}
  ProgressPercent=`curl -s --user admin:admin -H 'X-Requested-By:mycompany' -X GET http://${AmbariHost}:8080/api/v1/clusters/hdpcluster/requests/1 | grep progress_percent | awk '{print $3}' | cut -d . -f 1`
  echo " Progress: $ProgressPercent"

  while [[ `echo $ProgressPercent | grep -v 100` ]]; do
    ProgressPercent=`curl -s --user admin:admin -H 'X-Requested-By:mycompany' -X GET http://${AmbariHost}:8080/api/v1/clusters/hdpcluster/requests/1 | grep progress_percent | awk '{print $3}' | cut -d . -f 1`
    tput cuu1
    echo " Progress: $ProgressPercent %"
    sleep 2
  done
  echo ""
  echo "Cluster build is complete."
  echo "You may access the Ambari web interface at http://${AmbariHost}:8080"
  echo "User/pass: admin / admin"
}

## 
## Command parsing
## 

# Show help with run with no args
[ $# -eq 0 ] && PrintHelp && exit 0

# Process command
case $command in
  "start")
    [ $args ] && StartProfile $args || ListProfiles
    ;;
  "profile")
    [ $args ] && SetProfile $args || ListProfiles
    ;;
  "dns")
    UpdateDns
    ;;
  "deploy")
    Deploy
    ;;
  "blueprint")
    ApplyBlueprint mgmt.support.local
    ;;
  "halt")
    Halt
    ;;
  "suspend")
    Suspend
    ;;
  "resume")
    Resume
    ;;
  "destroy")
    Destroy
    ;;
  "status")
    Status $args
    ;;
  "ssh")
    [ $args ] && SSH $args || echo "Usage: $self ssh <host>"
    ;;
  "help")
    PrintHelp
    ;;
  *)
    echo "$self: unknown command"
    ;;
esac

echo ''
## EOF
